// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOEZJU_BDaa2MZI_Qo_zUXSCc-IPzRp4k',
    appId: '1:400662743294:web:af94eaaa165dbc8944bdaf',
    messagingSenderId: '400662743294',
    projectId: 'myfinance-126eb',
    authDomain: 'myfinance-126eb.firebaseapp.com',
    storageBucket: 'myfinance-126eb.firebasestorage.app',
    measurementId: 'G-BXQTJ77EY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdUV6mAhVc_x1VKZ45MGWeoPiwdBn91o',
    appId: '1:400662743294:android:1f59fb18157f13a444bdaf',
    messagingSenderId: '400662743294',
    projectId: 'myfinance-126eb',
    storageBucket: 'myfinance-126eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvEZQ57CYJp8b77AShB9qJJrE2QGtXT6o',
    appId: '1:400662743294:ios:584eb9f29ab3891844bdaf',
    messagingSenderId: '400662743294',
    projectId: 'myfinance-126eb',
    storageBucket: 'myfinance-126eb.firebasestorage.app',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvEZQ57CYJp8b77AShB9qJJrE2QGtXT6o',
    appId: '1:400662743294:ios:584eb9f29ab3891844bdaf',
    messagingSenderId: '400662743294',
    projectId: 'myfinance-126eb',
    storageBucket: 'myfinance-126eb.firebasestorage.app',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOEZJU_BDaa2MZI_Qo_zUXSCc-IPzRp4k',
    appId: '1:400662743294:web:e96b6a124c97dbd044bdaf',
    messagingSenderId: '400662743294',
    projectId: 'myfinance-126eb',
    authDomain: 'myfinance-126eb.firebaseapp.com',
    storageBucket: 'myfinance-126eb.firebasestorage.app',
    measurementId: 'G-DR0WLG5QDQ',
  );
}
